
POST http://localhost:4000/app/Game
Content-Type: application/json

{
    "fullName": "Sakashima",
    
    "score": "0"
}

//GET http://localhost:4000/app/Leaderboard
//Content-Type: application/json