
POST http://localhost:4000/app/Game
Content-Type: application/json

{
    "fullName": "Vegeta",
    
    "score": "9001"
}

//GET http://localhost:4000/app/Leaderboard
//Content-Type: application/json